第6回課題の提出
Taka898/RaiseTech pull request #5
Opened 2023-06-21 14:11 UTC by Taka898

Lecture06.mdで第6回課題を報告。

2023-06-21 23:45 UTC, MasatoshiMizumoto requested changes
1箇所、誤記ぽいので御確認お願いします！

2023-06-21 23:45 UTC, MasatoshiMizumoto commented on lecture06.md
> +- CloudWatchでアラーム状態になっていることを確認
ここOK状態の誤記ですかね？

2023-06-22 11:50 UTC, Taka898 commented on lecture06.md
> +- CloudWatchでアラーム状態になっていることを確認
OK状態の誤記でした！
提出前のチェックが甘かったです。

2023-06-22 12:11 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-06-23 07:26 UTC, merged